import type {
  CommentAttachment as SharedCommentAttachment,
  CommentAttachmentType as SharedCommentAttachmentType,
  IssueComment as SharedIssueComment,
  IssueCommentEditHistoryEntry as SharedIssueCommentEditHistoryEntry,
  ProjectQualityScoreConfig as SharedProjectQualityScoreConfig,
  QualityScoreItemId as SharedQualityScoreItemId,
  QualityScoreWeights as SharedQualityScoreWeights,
} from "@ideahome/shared";

export {
  AUTH_TOKEN_KEY,
  AUTH_TOKEN_SESSION_KEY,
  AUTH_TOKEN_COOKIE_KEY,
  AUTH_CHANGE_EVENT,
  ASSISTANT_VOICE_CHANGE_EVENT,
  isSkipLoginDev,
  getStoredToken,
  setStoredToken,
  clearStoredToken,
  getUserIdFromToken,
  getUserEmailFromToken,
  getUserScopedStorageKey,
  clearUserSavedData,
  isAuthenticated,
  getStoredOpenRouterModel,
  setStoredOpenRouterModel,
  getStoredAssistantVoiceUri,
  setStoredAssistantVoiceUri,
  logout,
  USER_SAVED_DATA_STORAGE_KEYS,
} from "./api/auth";

export {
  API_BASE,
  API_REQUEST_HEADER,
  BACKEND_CONNECTIVITY_CHANGE_EVENT,
  getApiBase,
  isBackendOffline,
  apiFetch,
  readResponseMessage,
  requestJson,
  requestBlob,
  requestVoid,
  sendErrorReportEmail,
} from "./api/http";

export const CALENDAR_EVENTS_CHANGED_EVENT = "ideahome-calendar-events-changed";

export {
  fetchProjects,
  fetchProjectMembers,
  fetchProjectInvites,
  fetchOrganizations,
  inviteProjectByEmail,
  inviteProjectMember,
  removeProjectMember,
  revokeProjectInvite,
  ensureOrganization,
  createOrganization,
  createProject,
  updateProject,
  deleteProject,
  fetchProjectCodeRepositories,
  fetchProjectPromptUsageTrend,
  fetchMyPromptUsage,
  clearMyPromptUsage,
  fetchCodexPromptUsage,
  optimizeProjectPrompt,
  createGithubRepositoryForProject,
  type Organization,
  type ProjectMember,
  type ProjectInvite,
  type Project,
  type ProjectCodeRepository,
  type ProjectCodeAnalysisRun,
  type PromptOptimizationResponse,
} from "./api/projects";

export {
  STATUSES,
  fetchIssues,
  fetchIssue,
  createIssue,
  updateIssue,
  updateIssueStatus,
  deleteIssue,
  deleteAllIssues,
  fetchIssueSearch,
  type Issue,
} from "./api/issues";

export {
  runUiTest,
  runApiTest,
  type RunUiTestResult,
  type RunApiTestResult,
} from "./api/tests";

export {
  fetchTodos,
  fetchTodoSearch,
  createTodo,
  updateTodo,
  deleteTodo,
  reorderTodos,
  fetchIdeas,
  fetchIdeaSearch,
  createIdea,
  updateIdea,
  deleteIdea,
  reorderIdeas,
  generateIdeaPlan,
  generateIdeaAssistantChat,
  generateListItemAssistantChat,
  fetchOpenRouterModels,
  fetchElevenLabsVoices,
  synthesizeIdeaChatSpeech,
  fetchCurrentWeather,
  fetchBugs,
  fetchBugSearch,
  createBug,
  updateBug,
  deleteBug,
  reorderBugs,
  fetchFeatures,
  fetchFeatureSearch,
  createFeature,
  updateFeature,
  deleteFeature,
  reorderFeatures,
  fetchEnhancements,
  createEnhancement,
  updateEnhancement,
  deleteEnhancement,
  reorderEnhancements,
  type Todo,
  type Idea,
  type IdeaPlan,
  type IdeaAssistantChatResult,
  type CurrentWeather,
  type Bug,
  type Feature,
  type Enhancement,
  type ElevenLabsVoice,
} from "./api/ideas";

export {
  fetchExpenses,
  createExpense,
  updateExpense,
  deleteExpense,
  fetchTaxDocuments,
  createTaxDocument,
  updateTaxDocument,
  deleteTaxDocument,
  downloadTaxDocument,
  deleteAllImportedExpenses,
  getPlaidLinkToken,
  exchangePlaidToken,
  fetchPlaidLinkedAccounts,
  renamePlaidLinkedAccount,
  syncPlaidTransactions,
  getPlaidLastSync,
  disconnectPlaidLinkedAccount,
  fetchCalendarGoogleStatus,
  startGoogleCalendarConnect,
  fetchGoogleCalendars,
  setGoogleCalendarSelection,
  syncGoogleCalendar,
  disconnectGoogleCalendar,
  fetchCalendarEvents,
  createCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
  type Expense,
  type PlaidLinkedAccount,
  type TaxDocument,
  type CalendarEvent,
  type CalendarGoogleStatus,
  type CalendarGoogleCalendar,
} from "./api/expenses";

export {
  fetchUsers,
  fetchMyAppearancePrefs,
  updateMyAppearancePrefs,
  fetchMyBulbyMemoryPrefs,
  updateMyBulbyMemoryPrefs,
  APPEARANCE_PRESETS,
  type User,
  type AppearancePresetId,
  type AppearancePreferences,
  type BulbyOrgContext,
  type BulbyRuleEntry,
  type BulbyMemoryPreferences,
} from "./api/users";

export {
  fetchIssueComments,
  createIssueComment,
  updateIssueComment,
  deleteIssueComment,
  addCommentAttachment,
  deleteCommentAttachment,
  uploadIssueRecording,
  updateIssueRecording,
  deleteIssueRecording,
  getRecordingUrl,
  uploadIssueScreenshot,
  updateIssueScreenshot,
  deleteIssueScreenshot,
  getScreenshotUrl,
  uploadIssueFile,
  updateIssueFile,
  deleteIssueFile,
  getIssueFileUrl,
} from "./api/issueMedia";

export type IssueCommentEditHistoryEntry = SharedIssueCommentEditHistoryEntry;
export type CommentAttachmentType = SharedCommentAttachmentType;
export type CommentAttachment = SharedCommentAttachment;
export type IssueComment = SharedIssueComment;
export type ProjectQualityScoreConfig = SharedProjectQualityScoreConfig;
export type QualityScoreItemId = SharedQualityScoreItemId;
export type QualityScoreWeights = SharedQualityScoreWeights;
