import { StyleSheet } from "react-native";
import { colors, radii, spacing } from "./tokens";

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bgPage,
  },
  topBar: {
    alignItems: "center",
    backgroundColor: colors.bgBar,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  brand: {
    color: colors.accentStrong,
    fontSize: 19,
    fontWeight: "600",
  },
  content: {
    flex: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  centeredFill: {
    alignItems: "center",
    flex: 1,
    gap: spacing.sm,
    justifyContent: "center",
  },
  authContainer: {
    flex: 1,
    gap: spacing.md,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  title: {
    color: colors.accentStrong,
    fontSize: 34,
    fontWeight: "700",
  },
  body: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  subtle: {
    color: colors.textMuted,
    fontSize: 13,
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
  },
  stack: {
    gap: spacing.sm,
  },
  stackFill: {
    flex: 1,
    gap: spacing.sm,
  },
  inlineRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  inlineRowWrap: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  spaceTop: {
    marginTop: spacing.sm,
  },
  flex: {
    flex: 1,
  },
  input: {
    backgroundColor: colors.bgCard,
    borderColor: colors.borderInput,
    borderRadius: radii.control,
    borderWidth: 1,
    color: colors.text,
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  addFormWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.8)",
    borderRadius: radii.card,
    padding: spacing.sm,
    backgroundColor: "rgba(37, 99, 235, 0.08)",
  },
  addFormInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  multilineInput: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  sectionLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  chip: {
    backgroundColor: "#f3f4f6",
    borderRadius: radii.small,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chipActive: {
    backgroundColor: colors.accentDark,
  },
  chipText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#ffffff",
  },
  fillCard: {
    flex: 1,
    minHeight: 180,
  },
  listContainer: {
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  listItem: {
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  listItemSelected: {
    borderWidth: 2.5,
    borderColor: colors.editModeBorder,
  },
  editModeWrap: {
    borderWidth: 2.5,
    borderColor: colors.editModeBorder,
    borderRadius: radii.control,
    padding: 1,
  },
  editModeWrapInner: {
    borderWidth: 1,
    borderColor: colors.editModeBorderInner,
    borderRadius: radii.control - 1,
    padding: spacing.sm,
  },
  checklistItemSelected: {
    borderWidth: 2.5,
    borderColor: colors.editModeBorder,
  },
  listItemTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  listItemMeta: {
    color: colors.textMuted,
    fontSize: 11,
  },
  column: {
    backgroundColor: colors.columnBg,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    padding: spacing.md,
    minWidth: 260,
    maxWidth: 280,
  },
  columnHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.sm,
    paddingHorizontal: 4,
  },
  columnTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
  },
  columnCount: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
    backgroundColor: colors.columnBg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    overflow: "hidden",
  },
  issueGroup: {
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  issueGroupHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  issueGroupTitle: {
    color: colors.accentStrong,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  issueCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 10,
    position: "relative",
  },
  issueCardTitle: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
    marginBottom: 8,
    paddingRight: 36,
  },
  issueCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  issueCardQualityScore: {
    position: "absolute",
    top: 8,
    right: 8,
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.columnBg,
    alignItems: "center",
    justifyContent: "center",
  },
  issueCardQualityScoreText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.text,
  },
  issueMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  issueMetaPill: {
    backgroundColor: "#eff6ff",
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: 5,
  },
  issueDetailSection: {
    backgroundColor: "#f8fafc",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  issueItem: {
    alignItems: "center",
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing.sm,
  },
  commentItem: {
    alignItems: "center",
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
    padding: spacing.sm,
  },
  commentAttachmentRow: {
    alignItems: "flex-start",
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
    padding: spacing.xs,
  },
  commentAttachmentPreview: {
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    height: 88,
    marginTop: spacing.xs,
    width: 140,
  },
  pendingAttachmentChip: {
    alignItems: "flex-start",
    backgroundColor: "#eef2ff",
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: 6,
  },
  pendingAttachmentPreview: {
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    height: 70,
    marginTop: spacing.xs,
    width: 110,
  },
  testResultPanel: {
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  testSuitePanel: {
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  testOutputText: {
    color: colors.textMuted,
    fontFamily: "Menlo",
    fontSize: 11,
    lineHeight: 15,
  },
  screenshotPreview: {
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    height: 120,
    width: "100%",
  },
  issueItemMain: {
    flex: 1,
    paddingRight: spacing.sm,
  },
  badge: {
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
    textTransform: "uppercase",
  },
  checklistItem: {
    alignItems: "center",
    backgroundColor: colors.bgCard,
    borderColor: colors.border,
    borderRadius: radii.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  doneToggle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "rgba(96, 165, 250, 0.8)",
    backgroundColor: "rgba(37, 99, 235, 0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  doneToggleChecked: {
    borderColor: "#93c5fd",
    backgroundColor: "rgba(59, 130, 246, 0.34)",
  },
  doneToggleCheck: {
    color: "#93c5fd",
    fontSize: 12,
    fontWeight: "700",
  },
  doneToggleEmptyDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: "rgba(191, 219, 254, 0.5)",
  },
  checklistMain: {
    flex: 1,
  },
  assistantPanel: {
    backgroundColor: "#f9fafb",
    borderColor: colors.border,
    borderRadius: radii.control,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.sm,
    padding: spacing.sm,
    width: "100%",
  },
  assistantMessage: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  doneText: {
    textDecorationLine: "line-through",
    opacity: 0.7,
  },
  bigValue: {
    color: colors.accentStrong,
    fontSize: 34,
    fontWeight: "700",
  },
  valueText: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "600",
  },
  previewOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.35)",
    flex: 1,
    justifyContent: "center",
    padding: spacing.md,
  },
  previewCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.card,
    flex: 1,
    maxHeight: "85%",
    overflow: "hidden",
    width: "100%",
  },
  previewWebView: {
    flex: 1,
  },
  modalOverlay: {
    backgroundColor: "rgba(0,0,0,0.4)",
    flex: 1,
    justifyContent: "center",
    padding: spacing.lg,
  },
  modalContent: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.card,
    maxHeight: "80%",
    padding: spacing.lg,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
});
