/**
 * @ideahome/shared — types and utilities shared between web and native app.
 */

export type {
  AuthProvider,
  AppTab,
  ChecklistKind,
  PendingCommentAttachment,
  TestExecutionResult,
  AssistantChatMessage,
} from "./types";

export {
  BUILT_IN_TABS,
  DEFAULT_TAB_ORDER,
  TAB_LABELS,
  getTabLabel,
  isAppTab,
  isCustomListTab,
} from "./tabs";

// Re-export config and path helpers so web and app can use one package
export {
  API_REQUEST_HEADER,
  ASSISTANT_VOICE_CHANGE_EVENT,
  AUTH_CHANGE_EVENT,
  AUTH_PARAM_ERROR,
  AUTH_PARAM_REDIRECT_URI,
  AUTH_PARAM_TOKEN,
  AUTH_TOKEN_COOKIE_KEY,
  AUTH_TOKEN_KEY,
  AUTH_TOKEN_SESSION_KEY,
  EXPENSE_CATEGORIES,
  IDEAHOME_API_ORIGIN,
  IDEAHOME_WEB_ORIGIN,
  ISSUE_STATUS_IDS,
  MOBILE_ACTIVE_TAB_STORAGE_KEY,
  MOBILE_AUTH_BYPASS_STORAGE_KEY,
  MOBILE_DEEP_LINK_REDIRECT_URI,
  MOBILE_SELECTED_PROJECT_STORAGE_KEY,
  MOBILE_TOKEN_STORAGE_KEY,
  JUST_LOGGED_IN_SESSION_KEY,
  NATIVE_BRIDGE_AUTH_CHANGE,
  NATIVE_BRIDGE_AUTH_ERROR,
  STATUS_OPTIONS,
  pathCommentAttachmentById,
  pathCommentAttachments,
  pathExpenseById,
  pathExpenses,
  pathIssueCommentById,
  pathIssueComments,
  pathIssueFileById,
  pathIssueFiles,
  pathIssueFileStream,
  pathIssueById,
  pathIssueRecordingById,
  pathIssueRecordings,
  pathIssueScreenshotById,
  pathIssueScreenshots,
  pathIssueStatus,
  pathIssues,
  pathIssuesBulk,
  pathOrganizations,
  pathOrganizationsEnsure,
  pathProjectById,
  pathProjects,
  pathRecordingStream,
  pathScreenshotStream,
  pathTestsRunApi,
  pathTestsRunUi,
  pathUsers,
  pathAuthApple,
  pathAuthGithub,
  pathAuthGoogle,
  pathAuthProviders,
  pathAuthMobile,
  pathApiUiTests,
  pathIdeaAssistantChat,
  pathIdeaPlan,
  pathIdeasAssistantChat,
  pathIdeasElevenlabsVoices,
  pathIdeasOpenrouterModels,
  pathIdeasTts,
  pathChecklistList,
  pathChecklistItem,
  pathChecklistReorder,
  projectNameToAcronym,
  readUrlParam,
  sanitizeAuthToken,
  testNameToSlug,
} from "@ideahome/shared-config";

export type {
  User,
  Project,
  Organization,
  Issue,
  IssueComment,
  IssueCommentEditHistoryEntry,
  CommentAttachment,
  CommentAttachmentType,
  Expense,
  ChecklistItem,
  IssueFile,
  IssueRecording,
  IssueScreenshot,
  CreateIssueInput,
  UpdateIssueInput,
  UpdateIssueStatusInput,
  CreateIssueCommentInput,
  UpdateIssueCommentInput,
  AddCommentAttachmentInput,
  CreateExpenseInput,
  UpdateExpenseInput,
  CreateProjectInput,
  UpdateProjectInput,
  RunUiTestInput,
  RunApiTestInput,
  RunUiTestResult,
  RunApiTestResult,
  NativeBridgeAuthChangePayload,
  NativeBridgeAuthErrorPayload,
  UITestFile,
  UITestSuite,
} from "@ideahome/shared-config";
