/**
 * @ideahome/shared — types and utilities shared between web and native app.
 */

export type {
  AuthProvider,
  AppTab,
  ChecklistKind,
  PendingCommentAttachment,
  TestExecutionResult,
  AssistantChatMessage,
  PromptUsageSource,
  PromptUsageTrendMode,
  PromptEfficiencyBreakdown,
  PromptUsageTrendPoint,
  PromptUsageDetailEntry,
  PromptUsageTrendResponse,
  PromptUsageMineResponse,
} from "./types";

export {
  buildPromptEfficiencyBreakdown,
  computePromptEfficiencyScore,
  buildPromptImprovementHints,
  buildOptimizedPrompt,
  buildPromptUsageDetail,
  buildShareablePromptCoachTemplate,
  type PromptUsageMetricsInput,
} from "./promptUsage";

export {
  BUILT_IN_TABS,
  DEFAULT_TAB_ORDER,
  TAB_LABELS,
  getTabLabel,
  isAppTab,
  isCustomListTab,
} from "./tabs";

export { toUiTitleCase } from "./uiTitleCase";

// Re-export config and path helpers so web and app can use one package
export {
  API_REQUEST_HEADER,
  ASSISTANT_VOICE_CHANGE_EVENT,
  AUTH_CHANGE_EVENT,
  AUTH_PARAM_ERROR,
  AUTH_PARAM_REDIRECT_URI,
  AUTH_PARAM_TOKEN,
  AUTH_TOKEN_COOKIE_KEY,
  AUTH_TOKEN_KEY,
  AUTH_TOKEN_SESSION_KEY,
  EXPENSE_CATEGORIES,
  IDEAHOME_API_ORIGIN,
  IDEAHOME_WEB_ORIGIN,
  QUALITY_SCORE_ITEM_IDS,
  DEFAULT_QUALITY_SCORE_WEIGHTS,
  APPEARANCE_PRESET_IDS,
  ISSUE_STATUS_IDS,
  MOBILE_ACTIVE_TAB_STORAGE_KEY,
  MOBILE_AUTH_BYPASS_STORAGE_KEY,
  MOBILE_DEEP_LINK_REDIRECT_URI,
  MOBILE_SELECTED_PROJECT_STORAGE_KEY,
  MOBILE_TOKEN_STORAGE_KEY,
  JUST_LOGGED_IN_SESSION_KEY,
  NATIVE_BRIDGE_AUTH_CHANGE,
  NATIVE_BRIDGE_AUTH_ERROR,
  STATUS_OPTIONS,
  pathCommentAttachmentById,
  pathCommentAttachments,
  pathExpenseById,
  pathExpenses,
  pathExpensesDeleteImported,
  pathIssueCommentById,
  pathIssueComments,
  pathIssueFileById,
  pathIssueFiles,
  pathIssueFileStream,
  pathIssueById,
  pathIssueRecordingById,
  pathIssueRecordings,
  pathIssueScreenshotById,
  pathIssueScreenshots,
  pathIssueStatus,
  pathIssues,
  pathIssuesBulk,
  pathOrganizations,
  pathOrganizationsEnsure,
  pathProjectById,
  pathProjectInvites,
  pathProjectMembers,
  pathProjects,
  pathRecordingStream,
  pathScreenshotStream,
  pathTestsRunApi,
  pathTestsRunUi,
  pathSupportErrorReport,
  pathUsers,
  pathUsersMeAppearance,
  pathAuthApple,
  pathAuthGithub,
  pathAuthGoogle,
  pathAuthProviders,
  pathAuthMobile,
  pathApiUiTests,
  pathCalendarGoogleStatus,
  pathCalendarGoogleConnect,
  pathCalendarGoogleCalendars,
  pathCalendarGoogleCalendarSelection,
  pathCalendarGoogleSync,
  pathCalendarEvents,
  pathCalendarEventById,
  pathIdeaAssistantChat,
  pathIdeaPlan,
  pathIdeasAssistantChat,
  pathIdeasElevenlabsVoices,
  pathIdeasOpenrouterModels,
  pathIdeasTts,
  pathIdeasWeather,
  pathProjectPromptUsageTrend,
  pathProjectMyPromptUsage,
  pathProjectMyPromptUsageClear,
  pathChecklistList,
  pathChecklistItem,
  pathChecklistReorder,
  projectNameToAcronym,
  createDefaultQualityScoreConfig,
  normalizeQualityScoreConfig,
  isProjectQualityScoreConfig,
  isQualityScoreItemComplete,
  computeQualityScorePercent,
  readUrlParam,
  sanitizeAuthToken,
  testNameToSlug,
} from "@ideahome/shared-config";

export type {
  User,
  AppearancePresetId,
  AppearancePreferences,
  Project,
  ProjectQualityScoreConfig,
  QualityScoreItemId,
  QualityScoreWeights,
  Organization,
  Issue,
  IssueComment,
  IssueCommentEditHistoryEntry,
  CommentAttachment,
  CommentAttachmentType,
  Expense,
  CalendarEvent,
  CreateCalendarEventInput,
  UpdateCalendarEventInput,
  CalendarGoogleStatus,
  CalendarGoogleCalendar,
  ChecklistItem,
  IssueFile,
  IssueRecording,
  IssueScreenshot,
  CreateIssueInput,
  UpdateIssueInput,
  UpdateIssueStatusInput,
  CreateIssueCommentInput,
  UpdateIssueCommentInput,
  AddCommentAttachmentInput,
  CreateExpenseInput,
  UpdateExpenseInput,
  CreateProjectInput,
  UpdateProjectInput,
  RunUiTestInput,
  RunApiTestInput,
  RunUiTestResult,
  RunApiTestResult,
  NativeBridgeAuthChangePayload,
  NativeBridgeAuthErrorPayload,
  UITestFile,
  UITestSuite,
} from "@ideahome/shared-config";
